/* Generated By:JavaCC: Do not edit this line. FilterParserConstants.java */
package com.alibaba.napoli.metamorphosis.filter;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FilterParserConstants {int EOF = 0;
int TRUE = 6;
int FALSE = 7;
int NULL = 8;
int AND = 9;
int NOT = 10;
int OR = 11;
int BETWEEN = 12;
int LIKE = 13;
int IN = 14;
int IS = 15;
int ESCAPE = 16;
int LPAREN = 17;
int RPAREN = 18;
int SEMICOLON = 19;
int COMMA = 20;
int MULT = 21;
int DIV = 22;
int MINUS = 23;
int PLUS = 24;
int GT = 25;
int GE = 26;
int LT = 27;
int LE = 28;
int NE = 29;
int EQ = 30;
int INTEGER_LITERAL = 31;
int DECIMAL_LITERAL = 32;
int HEX_LITERAL = 33;
int OCTAL_LITERAL = 34;
int FLOATING_POINT_LITERAL = 35;
int EXPONENT = 36;
int SIMPLE_STRING = 37;
int IDENTIFIER = 38;
int LETTER = 39;
int DIGIT = 40;

int DEFAULT = 0;

String[] tokenImage = {
  "<EOF>",
  "\" \"",
  "\"\\r\"",
  "\"\\t\"",
  "\"\\f\"",
  "\"\\n\"",
  "\"TRUE\"",
  "\"FALSE\"",
  "\"NULL\"",
  "\"AND\"",
  "\"NOT\"",
  "\"OR\"",
  "\"BETWEEN\"",
  "\"LIKE\"",
  "\"IN\"",
  "\"IS\"",
  "\"ESCAPE\"",
  "\"(\"",
  "\")\"",
  "\";\"",
  "\",\"",
  "\"*\"",
  "\"/\"",
  "\"-\"",
  "\"+\"",
  "\">\"",
  "\">=\"",
  "\"<\"",
  "\"<=\"",
  "\"<>\"",
  "\"=\"",
  "<INTEGER_LITERAL>",
  "<DECIMAL_LITERAL>",
  "<HEX_LITERAL>",
  "<OCTAL_LITERAL>",
  "<FLOATING_POINT_LITERAL>",
  "<EXPONENT>",
  "<SIMPLE_STRING>",
  "<IDENTIFIER>",
  "<LETTER>",
  "<DIGIT>",
};}
